name: PatataTube
options:
  bundleIdPrefix: com.patatatube
  deploymentTarget:
    iOS: "17.0"
packages:
  PatataTubeKit:
    path: ../PatataTubeKit
  Capture:
    url: https://github.com/bitdriftlabs/capture-ios.git
    from: "0.23.5"
  Clocks:
    url: https://github.com/pointfreeco/swift-clocks.git
    from: "1.1.0"
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    from: "0.10.3"
targets:
  PatataTube:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations: {}
        UILaunchStoryboardName: LaunchScreen
        "UISupportedInterfaceOrientations~iphone":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        UIBackgroundModes:
          - audio
    dependencies:
      - package: PatataTubeKit
      - package: Capture
        product: Capture
      - package: Clocks
    settings:
      base:
        DEVELOPMENT_TEAM: Q3WS4MWCW3
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.patatatube.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.1.5"
        CURRENT_PROJECT_VERSION: "62"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "6.0"
  PatataTubeTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Tests
    dependencies:
      - target: PatataTube
      - package: Clocks
      - package: ViewInspector
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.patatube.tests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "6.0"
schemes:
  PatataTube:
    build:
      targets:
        PatataTube: all
    test:
      targets:
        - PatataTubeTests
    archive:
      config: Release
