name: PatataTube
options:
  bundleIdPrefix: com.patatatube
  deploymentTarget:
    iOS: "17.0"
packages:
  PatataTubeKit:
    path: ../PatataTubeKit
targets:
  PatataTube:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Sources
    dependencies:
      - package: PatataTubeKit
    settings:
      base:
        DEVELOPMENT_TEAM: Q3WS4MWCW3
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.patatatube.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0.26"
        CURRENT_PROJECT_VERSION: "27"
        TARGETED_DEVICE_FAMILY: "2"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        SWIFT_VERSION: "6.0"
        INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsLocalNetworking: YES
        INFOPLIST_KEY_UIFileSharingEnabled: YES
        INFOPLIST_KEY_LSSupportsOpeningDocumentsInPlace: YES
schemes:
  PatataTube:
    build:
      targets:
        PatataTube: all
    archive:
      config: Release
